# Generated by Django 5.2.17 on 2026-08-27 15:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationModule",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=5, primary_key=True, serialize=False, verbose_name="código"
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True, verbose_name="slug")),
                ("name", models.CharField(max_length=140, verbose_name="nome")),
                ("short_description", models.CharField(max_length=320, verbose_name="descrição")),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("ai_agent", "Agente de IA"),
                            ("rpa", "RPA"),
                            ("control", "Controle sistematizado"),
                        ],
                        max_length=20,
                        verbose_name="natureza",
                    ),
                ),
                (
                    "complexity",
                    models.CharField(
                        choices=[("low", "Baixa"), ("medium", "Média"), ("high", "Alta")],
                        max_length=10,
                        verbose_name="complexidade",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diário"),
                            ("monthly", "Mensal"),
                            ("on_demand", "Sob demanda"),
                        ],
                        max_length=20,
                        verbose_name="frequência",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="habilitado")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="ordem")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
            ],
            options={
                "verbose_name": "módulo de automação",
                "verbose_name_plural": "módulos de automação",
                "ordering": ("sort_order", "code"),
            },
        ),
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Agendado")],
                        max_length=12,
                        verbose_name="origem",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("queued", "Na fila"),
                            ("running", "Em execução"),
                            ("awaiting_review", "Aguardando revisão"),
                            ("succeeded", "Concluída"),
                            ("succeeded_with_warnings", "Concluída com alertas"),
                            ("partially_failed", "Falha parcial"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="estado",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, verbose_name="parâmetros"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=180,
                        null=True,
                        unique=True,
                        verbose_name="chave de idempotência",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="resumo")),
                ("error_message", models.TextField(blank=True, verbose_name="erro apresentado")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadados")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="iniciada em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finalizada em"),
                ),
            ],
            options={
                "verbose_name": "execução",
                "verbose_name_plural": "execuções",
                "ordering": ("-created_at",),
            },
        ),
    ]
