# Generated by Django 5.2.17 on 2026-08-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("automations", "0001_initial"),
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="automationmodule",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="automation_modules",
                to="identity.area",
                verbose_name="área",
            ),
        ),
        migrations.AddField(
            model_name="automationrun",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="automations.automationmodule",
                verbose_name="módulo",
            ),
        ),
        migrations.AddField(
            model_name="automationrun",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automation_runs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="disparada por",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrun",
            index=models.Index(fields=["module", "-created_at"], name="run_module_created_idx"),
        ),
        migrations.AddIndex(
            model_name="automationrun",
            index=models.Index(fields=["status", "-created_at"], name="run_status_created_idx"),
        ),
    ]
