# Generated by Django 5.2.17 on 2026-08-30 05:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=120, unique=True, verbose_name="identificador"),
                ),
                ("client_name", models.CharField(max_length=180, verbose_name="cliente")),
                (
                    "client_document",
                    models.CharField(db_index=True, max_length=18, verbose_name="CPF/CNPJ"),
                ),
                (
                    "responsible_name",
                    models.CharField(max_length=180, verbose_name="responsável"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="e-mail de contato"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=24, verbose_name="telefone de contato"),
                ),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[("email", "E-mail"), ("whatsapp", "WhatsApp")],
                        default="email",
                        max_length=16,
                        verbose_name="canal preferencial",
                    ),
                ),
                ("valid_until", models.DateField(db_index=True, verbose_name="válido até")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("revoked", "Revogado"),
                            ("replaced", "Substituído"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
            ],
            options={
                "verbose_name": "certificado digital",
                "verbose_name_plural": "certificados digitais",
                "ordering": ("valid_until", "client_name", "serial_number"),
                "indexes": [
                    models.Index(
                        fields=["status", "valid_until"],
                        name="cert_status_expiry_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CertificateCommunication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_valid_until", models.DateField(verbose_name="validade considerada")),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "E-mail"), ("whatsapp", "WhatsApp")],
                        max_length=16,
                        verbose_name="canal",
                    ),
                ),
                ("policy_key", models.CharField(max_length=80, verbose_name="política")),
                ("recipient", models.CharField(max_length=254, verbose_name="destinatário")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviada"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="enviada em"),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="último erro")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizada em")),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communications",
                        to="automations.digitalcertificate",
                        verbose_name="certificado",
                    ),
                ),
                (
                    "first_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_communications",
                        to="automations.automationrun",
                        verbose_name="primeira execução",
                    ),
                ),
                (
                    "latest_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="latest_communications",
                        to="automations.automationrun",
                        verbose_name="execução mais recente",
                    ),
                ),
            ],
            options={
                "verbose_name": "comunicação de certificado",
                "verbose_name_plural": "comunicações de certificados",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CommunicationAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(verbose_name="tentativa")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviada"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                ("recipient", models.CharField(max_length=254, verbose_name="destinatário")),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="identificador no provedor",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="erro")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="conteúdo auditável"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finalizada em"),
                ),
                (
                    "communication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="automations.certificatecommunication",
                        verbose_name="comunicação",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communication_attempts",
                        to="automations.automationrun",
                        verbose_name="execução",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentativa de comunicação",
                "verbose_name_plural": "tentativas de comunicação",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["run", "status"],
                        name="attempt_run_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("communication", "sequence"),
                        name="uniq_communication_attempt_sequence",
                    ),
                    models.UniqueConstraint(
                        fields=("communication", "run"),
                        name="uniq_communication_attempt_run",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="certificatecommunication",
            index=models.Index(
                fields=["status", "-created_at"],
                name="comm_status_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificatecommunication",
            constraint=models.UniqueConstraint(
                fields=("certificate", "certificate_valid_until", "channel", "policy_key"),
                name="uniq_cert_expiry_channel_policy",
            ),
        ),
    ]
