# Generated by Django 5.2.17 on 2026-08-30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.automations.sc06.rules


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0003_digitalcertificate_certificatecommunication_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BriefingTemplate",
            fields=[
                (
                    "code",
                    models.SlugField(
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                        verbose_name="código",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
            ],
            options={
                "verbose_name": "template de briefing",
                "verbose_name_plural": "templates de briefing",
                "ordering": ("name", "code"),
            },
        ),
        migrations.CreateModel(
            name="BriefingTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="versão")),
                (
                    "schema",
                    models.JSONField(
                        default=dict,
                        validators=[core.automations.sc06.rules.validate_template_schema],
                        verbose_name="schema",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Rascunho"), ("published", "Publicada")],
                        default="draft",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="publicada em"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizada em")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_briefing_template_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="automations.briefingtemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "versão de template de briefing",
                "verbose_name_plural": "versões de templates de briefing",
                "ordering": ("template", "-version"),
            },
        ),
        migrations.CreateModel(
            name="SocietaryBriefing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_name", models.CharField(max_length=180, verbose_name="cliente")),
                (
                    "client_document",
                    models.CharField(max_length=40, verbose_name="número documental sintético"),
                ),
                ("answers", models.JSONField(blank=True, default=dict, verbose_name="respostas")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="concluído em"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_societary_briefings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="societary_briefing",
                        to="automations.automationrun",
                        verbose_name="execução",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="briefings",
                        to="automations.briefingtemplateversion",
                        verbose_name="versão do template",
                    ),
                ),
            ],
            options={
                "verbose_name": "briefing societário",
                "verbose_name_plural": "briefings societários",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="briefingtemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"),
                name="uniq_briefing_template_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="briefingtemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="briefing_version_gte_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="briefingtemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", True), ("status", "draft")),
                    models.Q(("published_at__isnull", False), ("status", "published")),
                    _connector="OR",
                ),
                name="briefing_publication_timestamp_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="societarybriefing",
            index=models.Index(
                fields=["status", "-created_at"],
                name="briefing_status_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="societarybriefing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", False), ("status", "completed")),
                    models.Q(
                        ("completed_at__isnull", True),
                        ("status__in", ("draft", "cancelled")),
                    ),
                    _connector="OR",
                ),
                name="briefing_completion_timestamp_consistent",
            ),
        ),
    ]
