# Generated by Django 5.2.17 on 2026-08-31 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_completion_actor(apps, schema_editor):
    briefing_model = apps.get_model("automations", "SocietaryBriefing")
    database = schema_editor.connection.alias
    pending = []
    queryset = (
        briefing_model.objects.using(database)
        .select_related("run")
        .filter(status="completed", completed_by__isnull=True)
    )
    for briefing in queryset.iterator():
        actor_id = briefing.created_by_id or briefing.run.triggered_by_id
        if actor_id is None:
            raise RuntimeError(
                "Não foi possível atribuir o autor de um briefing concluído existente."
            )
        briefing.completed_by_id = actor_id
        pending.append(briefing)
    if pending:
        briefing_model.objects.using(database).bulk_update(pending, ("completed_by",))


def clear_completion_actor(apps, schema_editor):
    briefing_model = apps.get_model("automations", "SocietaryBriefing")
    briefing_model.objects.using(schema_editor.connection.alias).update(completed_by=None)


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0004_briefingtemplate_briefingtemplateversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="societarybriefing",
            name="briefing_completion_timestamp_consistent",
        ),
        migrations.AddField(
            model_name="societarybriefing",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="completed_societary_briefings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="concluído por",
            ),
        ),
        migrations.RunPython(backfill_completion_actor, clear_completion_actor),
        migrations.AddConstraint(
            model_name="societarybriefing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", False),
                        ("completed_by__isnull", False),
                        ("status", "completed"),
                    ),
                    models.Q(
                        ("completed_at__isnull", True),
                        ("completed_by__isnull", True),
                        ("status__in", ("draft", "cancelled")),
                    ),
                    _connector="OR",
                ),
                name="briefing_completion_audit_consistent",
            ),
        ),
    ]
