# Generated by Django 5.2.17 on 2026-08-31 15:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0005_add_briefing_completion_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalClient",
            fields=[
                (
                    "code",
                    models.SlugField(
                        max_length=80, primary_key=True, serialize=False, verbose_name="código"
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="nome")),
                (
                    "document_number",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF/CNPJ sintético"),
                ),
                ("aliases", models.JSONField(blank=True, default=list, verbose_name="aliases")),
                (
                    "route_prefix",
                    models.SlugField(max_length=100, unique=True, verbose_name="pasta de destino"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
            ],
            options={
                "verbose_name": "cliente fiscal sintético",
                "verbose_name_plural": "clientes fiscais sintéticos",
                "ordering": ("name", "code"),
            },
        ),
        migrations.CreateModel(
            name="DocumentClassificationAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(verbose_name="tentativa")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Em processamento"),
                            ("succeeded", "Concluída"),
                            ("invalid_response", "Resposta inválida"),
                            ("failed", "Falhou"),
                        ],
                        default="processing",
                        max_length=24,
                        verbose_name="estado",
                    ),
                ),
                (
                    "provider",
                    models.CharField(default="openai", max_length=40, verbose_name="provedor"),
                ),
                ("model", models.CharField(blank=True, max_length=120, verbose_name="modelo")),
                (
                    "prompt_version",
                    models.CharField(max_length=80, verbose_name="versão do prompt"),
                ),
                (
                    "schema_version",
                    models.CharField(max_length=80, verbose_name="versão do schema"),
                ),
                (
                    "input_sha256",
                    models.CharField(max_length=64, verbose_name="hash da entrada minimizada"),
                ),
                (
                    "input_char_count",
                    models.PositiveIntegerField(default=0, verbose_name="caracteres enviados"),
                ),
                (
                    "provider_response_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="resposta do provedor"
                    ),
                ),
                (
                    "predicted_document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Nota fiscal"),
                            ("tax_payment", "Guia ou tributo"),
                            ("bank_statement", "Extrato financeiro"),
                            ("payroll", "Documento trabalhista"),
                            ("corporate_record", "Documento societário"),
                            ("other", "Outro documento"),
                            ("unknown", "Não identificado"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="tipo previsto",
                    ),
                ),
                (
                    "type_confidence",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=5, verbose_name="confiança no tipo"
                    ),
                ),
                (
                    "client_confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="confiança no cliente",
                    ),
                ),
                (
                    "is_ambiguous",
                    models.BooleanField(default=False, verbose_name="resultado ambíguo"),
                ),
                ("evidence", models.JSONField(blank=True, default=list, verbose_name="evidências")),
                (
                    "prediction",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="snapshot de candidatos"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=80, verbose_name="código de erro"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="erro operacional")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finalizada em"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_classification_attempts",
                        to="automations.automationrun",
                        verbose_name="execução",
                    ),
                ),
                (
                    "predicted_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classification_attempts",
                        to="automations.fiscalclient",
                        verbose_name="cliente previsto",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentativa de classificação",
                "verbose_name_plural": "tentativas de classificação",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FiscalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sha256", models.CharField(max_length=64, unique=True, verbose_name="SHA-256")),
                (
                    "storage_key",
                    models.CharField(max_length=500, unique=True, verbose_name="chave do original"),
                ),
                ("media_type", models.CharField(max_length=100, verbose_name="tipo de mídia")),
                ("byte_size", models.PositiveIntegerField(verbose_name="tamanho em bytes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Na fila"),
                            ("processing", "Em processamento"),
                            ("awaiting_review", "Aguardando revisão"),
                            ("routed", "Encaminhado"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=24,
                        verbose_name="estado",
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plain_text", "Texto"),
                            ("pdf_text", "Texto do PDF"),
                            ("ocr", "OCR"),
                        ],
                        max_length=20,
                        verbose_name="método de extração",
                    ),
                ),
                (
                    "extracted_text_sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="hash do texto extraído"
                    ),
                ),
                ("extracted_excerpt", models.TextField(blank=True, verbose_name="trecho extraído")),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="páginas"),
                ),
                (
                    "classified_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Nota fiscal"),
                            ("tax_payment", "Guia ou tributo"),
                            ("bank_statement", "Extrato financeiro"),
                            ("payroll", "Documento trabalhista"),
                            ("corporate_record", "Documento societário"),
                            ("other", "Outro documento"),
                            ("unknown", "Não identificado"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="tipo documental",
                    ),
                ),
                (
                    "type_confidence",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=5, verbose_name="confiança no tipo"
                    ),
                ),
                (
                    "client_confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="confiança no cliente",
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=list, verbose_name="evidências")),
                ("last_error", models.TextField(blank=True, verbose_name="último erro")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "matched_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="automations.fiscalclient",
                        verbose_name="cliente identificado",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento fiscal",
                "verbose_name_plural": "documentos fiscais",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pendente"), ("completed", "Concluída")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("low_confidence", "Confiança insuficiente"),
                            ("ambiguous_client", "Cliente ambíguo"),
                            ("unknown_client", "Cliente não identificado"),
                            ("unknown_type", "Tipo não identificado"),
                            ("classifier_unavailable", "Classificador indisponível"),
                            ("invalid_response", "Resposta inválida"),
                        ],
                        max_length=32,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "policy_version",
                    models.CharField(max_length=80, verbose_name="versão da política"),
                ),
                (
                    "resolved_document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Nota fiscal"),
                            ("tax_payment", "Guia ou tributo"),
                            ("bank_statement", "Extrato financeiro"),
                            ("payroll", "Documento trabalhista"),
                            ("corporate_record", "Documento societário"),
                            ("other", "Outro documento"),
                            ("unknown", "Não identificado"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="tipo confirmado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="resolvida em"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisada por",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_reviews",
                        to="automations.automationrun",
                        verbose_name="execução",
                    ),
                ),
                (
                    "suggested_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="automations.documentclassificationattempt",
                        verbose_name="predição sugerida",
                    ),
                ),
                (
                    "resolved_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_reviews",
                        to="automations.fiscalclient",
                        verbose_name="cliente confirmado",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="automations.fiscaldocument",
                        verbose_name="documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "revisão documental",
                "verbose_name_plural": "revisões documentais",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentIntake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Upload manual"),
                            ("simulated_inbox", "Caixa simulada"),
                        ],
                        max_length=24,
                        verbose_name="origem",
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="identificador na origem"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="nome original"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Na fila"),
                            ("duplicate", "Duplicado"),
                            ("processing", "Em processamento"),
                            ("awaiting_review", "Aguardando revisão"),
                            ("routed", "Encaminhado"),
                            ("failed", "Falhou"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=24,
                        verbose_name="estado",
                    ),
                ),
                ("is_duplicate", models.BooleanField(default=False, verbose_name="duplicado")),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="recebido em"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_intakes",
                        to="automations.automationrun",
                        verbose_name="execução",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intakes",
                        to="automations.fiscaldocument",
                        verbose_name="documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrada documental",
                "verbose_name_plural": "entradas documentais",
                "ordering": ("-received_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Nota fiscal"),
                            ("tax_payment", "Guia ou tributo"),
                            ("bank_statement", "Extrato financeiro"),
                            ("payroll", "Documento trabalhista"),
                            ("corporate_record", "Documento societário"),
                            ("other", "Outro documento"),
                            ("unknown", "Não identificado"),
                        ],
                        max_length=32,
                        verbose_name="tipo documental",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("automatic", "Automático"), ("human_review", "Revisão humana")],
                        max_length=20,
                        verbose_name="origem da decisão",
                    ),
                ),
                (
                    "policy_version",
                    models.CharField(max_length=80, verbose_name="versão da política"),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True, verbose_name="decidido em")),
                (
                    "classification_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="automations.documentclassificationattempt",
                        verbose_name="tentativa de origem",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decidido por",
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="automations.documentreview",
                        verbose_name="revisão",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_decisions",
                        to="automations.fiscalclient",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="automations.fiscaldocument",
                        verbose_name="documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "decisão documental",
                "verbose_name_plural": "decisões documentais",
                "ordering": ("-decided_at",),
            },
        ),
        migrations.AddField(
            model_name="documentclassificationattempt",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classification_attempts",
                to="automations.fiscaldocument",
                verbose_name="documento",
            ),
        ),
        migrations.CreateModel(
            name="DocumentRouting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(max_length=500, unique=True, verbose_name="chave encaminhada"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("routed", "Encaminhado"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="tentativas"),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="último erro")),
                (
                    "routed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="encaminhado em"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routing",
                        to="automations.documentdecision",
                        verbose_name="decisão",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_routings",
                        to="automations.automationrun",
                        verbose_name="execução",
                    ),
                ),
            ],
            options={
                "verbose_name": "encaminhamento documental",
                "verbose_name_plural": "encaminhamentos documentais",
                "ordering": ("-routed_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("last_error", ""),
                                ("routed_at__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("routed_at__isnull", True),
                                ("status", "failed"),
                                models.Q(("last_error", ""), _negated=True),
                            ),
                            models.Q(
                                ("attempt_count__gte", 1),
                                ("last_error", ""),
                                ("routed_at__isnull", False),
                                ("status", "routed"),
                            ),
                            _connector="OR",
                        ),
                        name="sc04_routing_status_consistent",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentRunItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("new", "Novo conteúdo"),
                            ("duplicate_source", "Origem já processada"),
                            ("duplicate_hash", "Conteúdo duplicado"),
                        ],
                        max_length=24,
                        verbose_name="resultado da ingestão",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_items",
                        to="automations.documentintake",
                        verbose_name="entrada",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_run_items",
                        to="automations.automationrun",
                        verbose_name="execução",
                    ),
                ),
            ],
            options={
                "verbose_name": "item de execução documental",
                "verbose_name_plural": "itens de execução documental",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(fields=["run", "outcome"], name="sc04_run_item_outcome_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("run", "intake"), name="uniq_sc04_run_intake")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="fiscaldocument",
            index=models.Index(
                fields=["status", "-created_at"], name="fiscal_doc_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscaldocument",
            index=models.Index(
                fields=["classified_type", "-created_at"], name="fiscal_doc_type_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_size__gt", 0)), name="sc04_doc_byte_size_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("type_confidence__gte", 0), ("type_confidence__lte", 1)),
                name="sc04_doc_type_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("client_confidence__gte", 0), ("client_confidence__lte", 1)),
                name="sc04_doc_client_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("resolved_at__isnull", True),
                        ("resolved_client__isnull", True),
                        ("resolved_document_type", "unknown"),
                        ("reviewed_by__isnull", True),
                        ("status", "pending"),
                    ),
                    models.Q(
                        ("resolved_at__isnull", False),
                        ("resolved_client__isnull", False),
                        ("reviewed_by__isnull", False),
                        ("status", "completed"),
                        models.Q(("resolved_document_type", "unknown"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="sc04_review_status_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="documentintake",
            index=models.Index(fields=["run", "status"], name="sc04_intake_run_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentintake",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                fields=("source", "source_reference"),
                name="uniq_sc04_source_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentintake",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_duplicate", True), ("status", "duplicate")),
                    models.Q(
                        ("is_duplicate", False), models.Q(("status", "duplicate"), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="sc04_intake_duplicate_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decided_by__isnull", True),
                        ("origin", "automatic"),
                        ("review__isnull", True),
                    ),
                    models.Q(
                        ("decided_by__isnull", False),
                        ("origin", "human_review"),
                        ("review__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="sc04_decision_origin_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("document_type", "unknown"), _negated=True),
                name="sc04_decision_type_known",
            ),
        ),
        migrations.AddIndex(
            model_name="documentclassificationattempt",
            index=models.Index(fields=["run", "status"], name="sc04_attempt_run_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentclassificationattempt",
            constraint=models.UniqueConstraint(
                fields=("document", "sequence"), name="uniq_sc04_document_attempt_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentclassificationattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("type_confidence__gte", 0), ("type_confidence__lte", 1)),
                name="sc04_attempt_type_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentclassificationattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("client_confidence__gte", 0), ("client_confidence__lte", 1)),
                name="sc04_attempt_client_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentclassificationattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("finished_at__isnull", True), ("status", "processing")),
                    models.Q(
                        ("finished_at__isnull", False),
                        ("status__in", ("succeeded", "invalid_response", "failed")),
                    ),
                    _connector="OR",
                ),
                name="sc04_attempt_finished_consistent",
            ),
        ),
    ]
