# Generated by Django 5.2.17 on 2026-09-01 09:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0006_sc04_document_classification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SC05Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_reference",
                    models.SlugField(max_length=80, unique=True, verbose_name="referência externa"),
                ),
                ("name", models.CharField(max_length=180, verbose_name="cliente")),
                (
                    "document",
                    models.CharField(
                        max_length=24, unique=True, verbose_name="documento sintético"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("blocked", "Bloqueado"),
                            ("partial", "Estado parcial"),
                            ("unknown", "A reconciliar"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="estado operacional",
                    ),
                ),
                (
                    "task_restore_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="responsáveis anteriores das tarefas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
            ],
            options={
                "verbose_name": "cliente do SC-05",
                "verbose_name_plural": "clientes do SC-05",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SC05Operation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("block", "Bloquear"), ("unblock", "Desbloquear")],
                        max_length=12,
                        verbose_name="ação",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("happy_path", "Fluxo normal"),
                            ("fail_tasks_apply", "Falha ao bloquear tarefas"),
                            ("timeout_accounting_apply", "Timeout no sistema contábil"),
                            (
                                "fail_tasks_apply_and_files_compensation",
                                "Falha em tarefas e na compensação de arquivos",
                            ),
                        ],
                        default="happy_path",
                        max_length=64,
                        verbose_name="cenário demonstrativo",
                    ),
                ),
                (
                    "resume_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="retomadas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizada em")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="automations.sc05client",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sc05_operation",
                        to="automations.automationrun",
                        verbose_name="execução",
                    ),
                ),
            ],
            options={
                "verbose_name": "operação do SC-05",
                "verbose_name_plural": "operações do SC-05",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SC05PortalStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "portal",
                    models.CharField(
                        choices=[
                            ("files", "Portal de arquivos"),
                            ("accounting", "Sistema contábil"),
                            ("tasks", "Sistema de tarefas"),
                        ],
                        max_length=20,
                        verbose_name="portal",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(verbose_name="ordem")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Em execução"),
                            ("applied", "Aplicado"),
                            ("unchanged", "Já estava correto"),
                            ("failed", "Falhou"),
                            ("compensated", "Compensado"),
                            ("compensation_failed", "Compensação falhou"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="estado",
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(blank=True, default=dict, verbose_name="estado anterior"),
                ),
                (
                    "desired_state",
                    models.JSONField(blank=True, default=dict, verbose_name="estado desejado"),
                ),
                (
                    "after_state",
                    models.JSONField(blank=True, default=dict, verbose_name="estado confirmado"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="erro operacional")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="iniciado em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finalizado em"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="automations.sc05operation",
                        verbose_name="operação",
                    ),
                ),
            ],
            options={
                "verbose_name": "etapa de portal do SC-05",
                "verbose_name_plural": "etapas de portal do SC-05",
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="SC05StepAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(verbose_name="tentativa")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("inspect", "Capturar estado"),
                            ("apply", "Aplicar"),
                            ("compensate", "Compensar"),
                        ],
                        max_length=16,
                        verbose_name="operação",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Em execução"),
                            ("succeeded", "Concluída"),
                            ("failed", "Falhou"),
                        ],
                        default="running",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                (
                    "state_before",
                    models.JSONField(blank=True, default=dict, verbose_name="estado antes"),
                ),
                (
                    "state_after",
                    models.JSONField(blank=True, default=dict, verbose_name="estado depois"),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=80, verbose_name="código de erro"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="erro operacional")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finalizada em"),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="automations.sc05portalstep",
                        verbose_name="etapa",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentativa de etapa do SC-05",
                "verbose_name_plural": "tentativas de etapa do SC-05",
                "ordering": ("sequence",),
            },
        ),
        migrations.CreateModel(
            name="SC05Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("screenshot", "Captura de tela")],
                        default="screenshot",
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(max_length=500, unique=True, verbose_name="chave privada"),
                ),
                ("sha256", models.CharField(max_length=64, verbose_name="SHA-256")),
                (
                    "content_type",
                    models.CharField(
                        default="image/png", max_length=100, verbose_name="tipo de mídia"
                    ),
                ),
                ("byte_size", models.PositiveIntegerField(verbose_name="tamanho em bytes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="automations.sc05stepattempt",
                        verbose_name="tentativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "artefato RPA do SC-05",
                "verbose_name_plural": "artefatos RPA do SC-05",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="sc05operation",
            index=models.Index(fields=["client", "-created_at"], name="sc05_op_client_created_idx"),
        ),
        migrations.AddIndex(
            model_name="sc05portalstep",
            index=models.Index(
                fields=["operation", "status"], name="sc05_step_operation_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sc05portalstep",
            constraint=models.UniqueConstraint(
                fields=("operation", "portal"), name="uniq_sc05_operation_portal"
            ),
        ),
        migrations.AddConstraint(
            model_name="sc05portalstep",
            constraint=models.UniqueConstraint(
                fields=("operation", "position"), name="uniq_sc05_operation_position"
            ),
        ),
        migrations.AddIndex(
            model_name="sc05stepattempt",
            index=models.Index(fields=["step", "status"], name="sc05_attempt_step_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="sc05stepattempt",
            constraint=models.UniqueConstraint(
                fields=("step", "sequence"), name="uniq_sc05_step_attempt_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="sc05stepattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("error_code", ""),
                        ("error_message", ""),
                        ("finished_at__isnull", True),
                        ("status", "running"),
                    ),
                    models.Q(
                        ("error_code", ""),
                        ("error_message", ""),
                        ("finished_at__isnull", False),
                        ("status", "succeeded"),
                    ),
                    models.Q(
                        ("finished_at__isnull", False),
                        ("status", "failed"),
                        models.Q(("error_code", ""), _negated=True),
                        models.Q(("error_message", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="sc05_attempt_status_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="sc05artifact",
            constraint=models.UniqueConstraint(
                fields=("attempt", "kind"), name="uniq_sc05_attempt_artifact_kind"
            ),
        ),
    ]
