# Generated by Django 5.2.17 on 2026-09-03 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0007_sc05client_sc05operation_sc05portalstep_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="automationmodule",
            options={
                "ordering": ("code",),
                "verbose_name": "módulo de automação",
                "verbose_name_plural": "módulos de automação",
            },
        ),
    ]
