# Generated by Django 5.2.17 on 2026-09-08 20:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0009_automationrun_delivery_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRunEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="sequência")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Criada"),
                            ("queued", "Enfileirada"),
                            ("dispatch_started", "Publicação iniciada"),
                            ("dispatch_failed", "Publicação falhou"),
                            ("broker_published", "Publicação confirmada"),
                            ("delivery_received", "Entrega recebida"),
                            ("delivery_ignored", "Entrega ignorada"),
                            ("delivery_finished", "Entrega finalizada"),
                            ("started", "Iniciada"),
                            ("heartbeat", "Sinal de atividade"),
                            ("requeued", "Reenfileirada"),
                            ("quarantined", "Isolada para reconciliação"),
                            ("resumed", "Retomada"),
                            ("review_required", "Revisão necessária"),
                            ("step_started", "Etapa iniciada"),
                            ("step_finished", "Etapa finalizada"),
                            ("attempt_started", "Tentativa iniciada"),
                            ("attempt_finished", "Tentativa finalizada"),
                            ("integration_started", "Integração iniciada"),
                            ("integration_finished", "Integração finalizada"),
                            ("integration_unknown", "Resultado da integração desconhecido"),
                            ("reconciliation_failed", "Reconciliação falhou"),
                            ("succeeded", "Concluída"),
                            ("succeeded_with_warnings", "Concluída com alertas"),
                            ("partially_failed", "Falha parcial"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelada"),
                        ],
                        max_length=40,
                        verbose_name="tipo do evento",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Portal"),
                            ("worker", "Worker"),
                            ("scheduler", "Agendador"),
                            ("reconciler", "Reconciliador"),
                            ("admin", "Administração técnica"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="origem do evento",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pendente"),
                            ("queued", "Na fila"),
                            ("running", "Em execução"),
                            ("awaiting_review", "Aguardando revisão"),
                            ("succeeded", "Concluída"),
                            ("succeeded_with_warnings", "Concluída com alertas"),
                            ("partially_failed", "Falha parcial"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelada"),
                        ],
                        max_length=32,
                        verbose_name="estado anterior",
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pendente"),
                            ("queued", "Na fila"),
                            ("running", "Em execução"),
                            ("awaiting_review", "Aguardando revisão"),
                            ("succeeded", "Concluída"),
                            ("succeeded_with_warnings", "Concluída com alertas"),
                            ("partially_failed", "Falha parcial"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelada"),
                        ],
                        max_length=32,
                        verbose_name="estado atual",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, max_length=100, verbose_name="requisição"),
                ),
                ("task_id", models.UUIDField(blank=True, null=True, verbose_name="entrega")),
                ("pulse_id", models.UUIDField(blank=True, null=True, verbose_name="pulso")),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=80, verbose_name="tipo da entidade"),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="identificador da entidade"
                    ),
                ),
                ("step", models.CharField(blank=True, max_length=80, verbose_name="etapa")),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="tentativa"
                    ),
                ),
                ("outcome", models.CharField(blank=True, max_length=64, verbose_name="resultado")),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=80, verbose_name="código de erro"),
                ),
                (
                    "duration_ms",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="duração em ms"
                    ),
                ),
                (
                    "deduplication_key",
                    models.CharField(max_length=180, verbose_name="chave de deduplicação"),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=500, verbose_name="mensagem segura"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="detalhes minimizados"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ocorrido em",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="automation_run_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ator",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="automations.automationrun",
                        verbose_name="execução",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de execução",
                "verbose_name_plural": "eventos de execução",
                "ordering": ("run_id", "sequence"),
                "indexes": [
                    models.Index(fields=["run", "-occurred_at"], name="run_event_run_time_idx"),
                    models.Index(
                        fields=["event_type", "-occurred_at"], name="run_event_type_time_idx"
                    ),
                    models.Index(fields=["entity_type", "entity_id"], name="run_event_entity_idx"),
                    models.Index(fields=["task_id"], name="run_event_task_idx"),
                    models.Index(fields=["request_id"], name="run_event_request_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "sequence"), name="uniq_run_event_sequence"
                    ),
                    models.UniqueConstraint(
                        fields=("run", "deduplication_key"), name="uniq_run_event_dedupe"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)), name="run_event_sequence_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duration_ms__isnull", True), ("duration_ms__gte", 0), _connector="OR"
                        ),
                        name="run_event_duration_nonnegative",
                    ),
                ],
            },
        ),
    ]
