# Generated by Django 5.2.17 on 2026-09-01 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulatorClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_id",
                    models.SlugField(
                        max_length=80, unique=True, verbose_name="identificador externo"
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="nome")),
                (
                    "document",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF/CNPJ sintético"),
                ),
            ],
            options={
                "verbose_name": "cliente do simulador",
                "verbose_name_plural": "clientes do simulador",
                "ordering": ("name", "external_id"),
            },
        ),
        migrations.CreateModel(
            name="SimulatorTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reference",
                    models.SlugField(max_length=80, unique=True, verbose_name="referência"),
                ),
                ("title", models.CharField(max_length=240, verbose_name="título")),
                ("assignee", models.CharField(max_length=180, verbose_name="responsável")),
                (
                    "previous_assignee",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="responsável anterior"
                    ),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="aberta")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="sc05_simulator.simulatorclient",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarefa do simulador",
                "verbose_name_plural": "tarefas do simulador",
                "ordering": ("client__name", "reference"),
            },
        ),
        migrations.CreateModel(
            name="SimulatorServiceAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[("files", "Arquivos"), ("accounting", "Contábil")],
                        max_length=20,
                        verbose_name="sistema",
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False, verbose_name="bloqueada")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_accounts",
                        to="sc05_simulator.simulatorclient",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "conta de serviço do simulador",
                "verbose_name_plural": "contas de serviço do simulador",
                "ordering": ("system", "client__name", "client__external_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "system"), name="sc05_sim_unique_client_system"
                    )
                ],
            },
        ),
    ]
