import { watch } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sources = [
  resolve(root, "node_modules/htmx.org/dist/htmx.min.js"),
  resolve(root, "node_modules/alpinejs/dist/cdn.min.js"),
  resolve(root, "src/static_src/app.js"),
];
const output = resolve(root, "src/static/js/app.js");

async function build() {
  const content = await Promise.all(sources.map((source) => readFile(source, "utf8")));
  await mkdir(dirname(output), { recursive: true });
  await writeFile(
    output,
    `/* SheepContabil browser bundle — generated by scripts/build-js.mjs */\n${content.join("\n;\n")}`,
    "utf8",
  );
  process.stdout.write(`JavaScript gerado em ${output}\n`);
}

await build();

if (process.argv.includes("--watch")) {
  for (const source of sources) {
    watch(source, { persistent: true }, async () => {
      try {
        await build();
      } catch (error) {
        process.stderr.write(`${error}\n`);
      }
    });
  }
}
